services:
  app:
    build: .
    container_name: farmatodo-api
    ports:
      - "8080:8080" # Puerto externo:interno
    depends_on:
      - db

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/farmatodo_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      API_KEY_SECRET: ${API_KEY_SECRET}
      APP_ENCRYPTION_KEY: ${APP_ENCRYPTION_KEY}
      MAILJET_API_KEY: ${MAILJET_API_KEY}
      MAILJET_SECRET_KEY: ${MAILJET_SECRET_KEY}

      MAIL_FROM_EMAIL: ${MAIL_FROM_MAIL}

  # 2. Base de Datos
  db:
    image: postgres:16-alpine
    container_name: farmatodo-db
    restart: always
    environment:
      - POSTGRES_DB=farmatodo_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432" # Host:5433 -> Contenedor:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: