name: Farmatodo CI/CD Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  # --- JOB 1: CONSTRUIR Y PROBAR ---
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del c贸digo
        uses: actions/checkout@v4

      - name: Configurar Java 25 (Eclipse Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'maven'

      - name: Dar permisos de ejecuci贸n a Maven Wrapper
        run: chmod +x mvnw

      - name: Compilar y Ejecutar Tests
        run: ./mvnw clean verify

      # ---  NUEVO PASO: Guardar el JAR generado ---
      - name: Subir Artefacto (JAR)
        uses: actions/upload-artifact@v4
        with:
          name: app-jar             # Nombre temporal del archivo en la nube de GitHub
          path: target/*.jar        # Qu茅 archivo queremos guardar
          retention-days: 1         # Guardarlo solo por 1 d铆a (ahorra espacio)

  # --- JOB 2: CONSTRUIR DOCKER ---
  build-push-docker:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout del c贸digo
        uses: actions/checkout@v4

      # ---  NUEVO PASO: Descargar el JAR del paso anterior ---
      - name: Descargar Artefacto (JAR)
        uses: actions/download-artifact@v4
        with:
          name: app-jar             # Tiene que coincidir con el nombre de arriba
          path: target              # D贸nde ponerlo (para que el Dockerfile lo encuentre)

      - name: Login en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Construir y Subir Imagen Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/farmatodo-challenge:latest